package com.evtnet.evtnetback.controller;

import com.evtnet.evtnetback.entity.PorcentajeReintegroCancelacionInscripcion;
import com.evtnet.evtnetback.service.PorcentajeReintegroCancelacionInscripcionServiceImpl;

public class PorcentajeReintegroCancelacionInscripcionController extends BaseControllerImpl <PorcentajeReintegroCancelacionInscripcion, PorcentajeReintegroCancelacionInscripcionServiceImpl> {
    
}
